### ISSUE TITLE
Use tensorflow instead of tf

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow-tensorflow#12]
This stands for package name, module name, etc. This should be consistent with the `tensorflow` itself, which uses the full name everywhere.

**Comment by petrbel** [comment]
I agree, however, `from cxflow_tf ...` is much shorter. This would be consistent with `cxflow_cntk` which we don't expand to "Cognitive Toolkit" either.

**Comment by FloopCZ** [comment]
@petrbel `cntk` itself uses [cntk](https://github.com/Microsoft/CNTK/blob/release/2.1/Examples/Image/Classification/MLP/Python/SimpleMNIST.py), however, `tensorflow` uses [tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist.py#L35), not `tf`. I would rather stay consistent with the upstream projects. You can always do `import cxflow_tensorflow as `cxtf` or whatever.

**Comment by blazekadam** [comment]
+1
